### ISSUE TITLE
Error when trying to get an overview graph

### ISSUE THREAD

**Issue by Chruut** [Giatomo/CuRveR#1]
Hello everyone and thank you for creating this awesome pipeline! I'm currently trying to use CuRveR to display Figure 6a of your published protocol about measuring bacterial predation. The overview tab is where I'm getting stuck. 

It gives me the following error message: 
* At least one layer must contain all faceting variables: `condition`.
* Plot is missing `condition`
* Layer 1 is missing `condition`
* 185: <Anonymous>

I used "Time" for the "X Data" and all the measured wells with data in them for the "Y Data(s)" and I'm pretty sure that I formatted all the sheets correctly. 
In the Cutoffs tab I'm able to see the different graphs. 
On stackoverflow people say that not the right datatype is fed into ggplot facet_wrap(). Maybe this helps. 

Besides that there is a text field on the right side of the first tab for which I don't know what I'm supposed to insert.

**Comment by Giatomo** [comment]
Sorry for the delay, this issue should be fixed. Just download CuRveR again and don't hesitate if you still have some issues !
